# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TeShHjx5Bb9w2kbVDEQLknzxNrzmg2Yo
"""

base = 10
height = 4
area = ((base * height) / 2)
print(area)

fenceLength = 15
gardenPerimeter = 260
numberFences = (gardenPerimeter /15 )
print(numberFences)

total_cents = 835


dollars = total_cents // 100
remaining_cents = total_cents % 100

quarters = remaining_cents // 25
remaining_cents = remaining_cents % 25


dimes = remaining_cents // 10


print("Total Amount:", total_cents, "cents")
print("Quarters:", quarters)
print("Dimes:", dimes)
print("Dollars:", dollars)

print("One\n\nTwo\n\nThree")

name = input("Enter your name: ")


print(name,  "is a common name.")

file_path = "C:\\Users\\Documents\\MyFile.txt"


print(file_path)